<div class="wrap">

	<div class="clearfix">
		<h1>Extend</h1>
	</div>

	<div class="column full first last">
		<a class="item" href="/admin/fields">
			<strong>Custom Fields</strong>
			<span>Create additional fields</span>
		</a>
		<a class="item" href="/admin/vars">
			<strong>Site Variables</strong>
			<span>Create additional metadata</span>
		</a>
		<a class="item" href="/admin/meta">
			<strong>Site Metadata</strong>
			<span>Manage your site data</span>
		</a>
		<a class="item" href="/admin/plugins">
			<strong>Plugins</strong>
			<span>Build you own</span>
		</a>
	</div>

</div>
