
<header>
	<h2>Posts</h2>

	<a class="btn" href="/admin/posts/create">Create a new post</a>

	<div class="pull-right">
		<form method="get" action="/admin/posts">
			<p><input placeholder="Search posts&hellip;" name="search">
				<button type="submit">Search</button></p>
		</form>
	</div>
</header>

<main class="grid">
	<div class="grid-col grid-1-3">
		<p>Filter by status</p>
		<ul>
			<li><a href="<?php echo url('/admin/posts'); ?>">All</a></li>
			<?php foreach($statuses as $status => $title): ?>
			<li><a href="/admin/posts?status=<?php echo $status; ?>"><?php echo $title; ?></a></li>
			<?php endforeach; ?>
		</ul>

		<p>Filter by categories</p>
		<ul>
			<?php foreach($categories as $category): ?>
			<li><a href="/admin/posts?category=<?php echo $category->id; ?>"><?php echo $category->title; ?></a></li>
			<?php endforeach; ?>
		</ul>
	</div>

	<div class="grid-col grid-2-3">
		<ul class="listing">
			<?php foreach($posts as $post): ?>
			<li>
				<a href="<?php echo url('/admin/posts/'.$post->id.'/edit'); ?>"><?php echo $post->title; ?></a>

				<span class="badge <?php echo $post->status; ?>"><?php echo ucwords($post->status); ?></span>

				<dl>
					<dt>Posted by</dt>
					<dd><a href="<?php echo url('/admin/users/'.$post->author); ?>">admin</a></dd>

					<dt>Filed under</dt>
					<dd><a href="<?php echo url('/admin/posts?category='.$post->category); ?>"><?php echo $category->title; ?></a></dd>

					<dt>Last edited</dt>
					<dd><?php echo $post->modified; ?></dd>
				</dl>
			</li>
			<?php endforeach; ?>
		</ul>

		<?php echo $paging->links(); ?>
	</div>
</main>
