
<div class="wrap">

	<header class="heading">
		<h2>Posts</h2>

		<div class="button-group">
			<form class="inline" method="get" action="/admin/posts">
				<p><input placeholder="Search posts&hellip;" name="search">
					<button class="btn" type="submit">Search</button>
					<a class="btn primary" href="/admin/posts/create">Create a new post</a></p>
			</form>
		</div>
	</header>

	<main class="grid">
		<div class="grid-col grid-1-4">
			<p>Filter by status</p>
			<ul>
				<li><a href="<?php echo url('/admin/posts'); ?>">All</a></li>
				<?php foreach($statuses as $status => $title): ?>
				<li><a href="/admin/posts?status=<?php echo $status; ?>"><?php echo $title; ?></a></li>
				<?php endforeach; ?>
			</ul>

			<p>Filter by categories</p>
			<ul>
				<?php foreach($categories as $category): ?>
				<li><a href="/admin/posts?category=<?php echo $category->id; ?>"><?php echo $category->title; ?></a></li>
				<?php endforeach; ?>
			</ul>
		</div>

		<div class="grid-col grid-3-4">
			<ul class="listing">
				<?php foreach($posts as $post): ?>
				<li>
					<h3><a href="<?php echo url('/admin/posts/'.$post->id.'/edit'); ?>"><?php echo $post->title; ?></a></h3>
					<span class="badge <?php echo $post->status; ?>"><?php echo $post->status; ?></span>
					<p><time class="quiet"><?php echo $post->getRelativeModifiedDate(); ?></time></p>
				</li>
				<?php endforeach; ?>
			</ul>

			<?php echo $paging->links(); ?>
		</div>
	</main>

</div>
