
<div class="wrap">
	<header class="heading">
		<h2>Plugins</h2>
	</header>

	<main>
		<ul class="listing">
			<?php foreach($plugins as $plugin): ?>
			<li>
				<h3><?php echo $plugin->getName(); ?></h3>
				<p><?php echo $plugin->getSummary(); ?></p>
				<span class="badge badge--pinned"><?php echo $plugin->getVersion(); ?></span>
				<p><a href="/admin/plugins/<?php echo $plugin->getFolder(); ?>/activate" class="button button--small">Activate</a></p>
			</li>
			<?php endforeach; ?>
		</ul>
	</main>
</div>
