<div class="wrap">
    <header class="heading">
        <h2><?php echo $title; ?></h2>

        <div class="button-group">
            <form class="form--inline" method="get" action="/admin/plugins/install">
                <p><input placeholder="Search repository&hellip;" name="search">
                    <button class="button" type="submit">Search</button>
                    <a class="button button--primary" href="/admin/plugins/install/upload">Upload manually</a></p>
            </form>
        </div>
    </header>

    <style>
        /* temporary until moving to CSS file */

        .listing .plugin {
            position: relative;
        }

        .listing .plugin .plugin-icon {
            position: relative;
            width: 60px;
            height: 60px;
            float: left;
            margin: 1rem 1rem 1rem 0;
            border-radius: 30px;
            background: rgba(0, 0, 0, .15);
        }

        .listing .plugin .plugin-icon::after {
            content: attr(data-plugin-first-letters);
            display: block;
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            line-height: 60px;
            text-align: center;
            font-size: 30px;
            font-weight: bold;
            color: #f0f3f6;
        }

        .listing .plugin .button-group {
            position: absolute;
            right: 0;
            top: 50%;
            transform: translateY(-50%);
            padding: 0 1rem;
        }
    </style>
    <main>
        <ul class="listing">
            <li class="plugin">
                <div class="plugin-icon" data-plugin-first-letters="CF"></div>
                <h3><a href="http://plugins.anchorcms.com/contact-form">Contact Form</a></h3>
                <p class="text--quiet">Just a basic contact form</p>
                <div class="button-group">
                    <a href="/admin/plugins/install/contact-form" class="button button--primary">Download</a>
                </div>
            </li>

            <li class="plugin">
                <div class="plugin-icon" data-plugin-first-letters="F"></div>
                <h3><a href="http://plugins.anchorcms.com/fooify">Fooify</a></h3>
                <p class="text--quiet">Replace the content of your pages with "foo"! Awesome!</p>
                <div class="button-group">
                    <a href="/admin/plugins/install/fooify" class="button button--primary">Download</a>
                </div>
            </li>
        </ul>
    </main>
</div>
