<div class="wrap">
    <header class="heading">
        <h2><?php echo $title; ?></h2>
        <div class="button-group">
            <?php if ($plugin->isActive()): ?>
                <form class="form--inline" action="/admin/plugins/<?php echo strtolower($plugin->getName()); ?>/disable"
                      method="post">
                    <p>
                        <button class="button button--danger">Disable</button>
                        <button type="button" class="button button--primary check-plugin-version"
                                data-plugin-name="<?php echo strtolower($plugin->getName()); ?>"
                                data-plugin-version="<?php echo $plugin->getVersion(); ?>">Check for updates
                        </button>
                    </p>
                </form>
            <?php else: ?>
                <form class="form--inline" action="/admin/plugins/<?php echo strtolower($plugin->getName()); ?>/enable"
                      method="post">
                    <p>
                        <button class="button button--primary">Enable</button>
                    </p>
                </form>
            <?php endif; ?>
        </div>
        <p><?php echo $plugin->getDescription(); ?></p>
    </header>

    <?php echo $messages; ?>

    <main>
        <h3>Plugin settings</h3>
        <section class="settings">
            <?php echo $this->render('partials/form', ['form' => $options]); ?>
        </section>

        <h3>Plugin meta</h3>
        <?php if ($plugin->isCorePlugin()): ?>
            <span>This is a core plugin. It cannot be removed.</span>
        <?php endif; ?>
        <ul class="listing">
            <li>
                <h4>Version</h4>
                <span><?php echo $plugin->getVersion(); ?></span>
            </li>
            <li>
                <h4>Homepage</h4>
                <span><a href="<?php echo $plugin->getUrl(); ?>"><?php echo $plugin->getUrl(); ?></a></span>
            </li>
            <li>
                <h4>Author</h4>
                <span><?php echo $plugin->getAuthor(); ?></span>
            </li>
        </ul>
    </main>
</div>
<script src="/assets/js/plugins.js"></script>
