<div class="debug-info wrap">
	<p>Database Queries</p>

	<table>
		<thead>
			<tr>
				<th>SQL</th>
				<th>Params</th>
				<th>Time</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($profile as $query): ?>
			<tr>
				<td><code><?php echo $this->e($query['sql']); ?></code></td>
				<td><code><?php echo $this->e(json_encode($query['params'])); ?></code></td>
				<td><?php echo round($query['executionMS'] * 1000, 2); ?>ms</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>

	<p>Memory <?php echo $memory; ?>mb, Execution time <?php echo $execution_time; ?>ms</p>
</div>
