<?php echo $form->open(); ?>

	<?php foreach($form->getElementsExcluding(['submit']) as $element): ?>

	<p><?php if($element->hasLabel()): ?>
		<label><?php echo $element->getLabel(); ?></label>
		<?php echo $element->getHtml(); ?>
	<?php else: ?>
		<?php echo $element->getHtml(); ?>
	<?php endif; ?>
	</p>

	<?php endforeach; ?>

	<p><?php echo $form->getElement('submit')->getHtml(); ?></p>

<?php echo $form->close(); ?>
