<?php echo $messages; ?>

<div class="form">
	<?php echo $form->open(); ?>
		<p style="float: right;">Forgotten Your password?</p>

		<?php echo $form->getElement('token')->getHtml(); ?>

		<?php foreach($form->getElementsExcluding(['submit', 'token']) as $element): ?>

		<p class="field<?php if($element->getType()) echo ' input'; ?> <?php echo $element->getAttribute('name'); ?>">
			<?php if($element->hasLabel()): ?>
				<label for="<?php echo $element->getAttribute('name'); ?>"><?php echo $element->getLabel(); ?></label>
			<?php endif; ?>

			<?php echo $element->getHtml(); ?>
		</p>

		<?php endforeach; ?>

		<p class="submit">
			<?php echo $form->getElement('submit')->getHtml(); ?>
			<a class="btn subdued" href="/admin">Nope, return to login.</a>
		</p>

	<?php echo $form->close(); ?>
</div>
