<?php echo $messages; ?>

<section class="content wrap autoclear">
	<nav class="rolodex">
		<header>
			<b>All users</b>

			<a class="btn" href="/admin/users/create">Create new</a>
		</header>

		<?php foreach($users as $user): ?>
		<a <?php if($current->id === $user->id) echo 'class="active"'; ?> href="/admin/users/<?php echo $user->id; ?>/edit">
			<img src="/assets/img/avatar.png" class="avatar default">
			<b><?php echo $user->real_name; ?></b>
			<span class="username"><?php echo $user->username; ?></span>
			<span class="badge <?php echo $user->role; ?>"><?php echo ucwords($user->role); ?></span>
		</a>
		<?php endforeach; ?>

		<?php echo $paging->links(); ?>
	</nav>

	<main>
		<h1>Editing &ldquo;<?php echo $current->username; ?>&rdquo;</h1>
		<?php echo $this->render('partials/form', ['form' => $form]); ?>
	</main>
</section>