
<div class="wrap">
	<header class="heading">
		<h2>Users</h2>

		<div class="button-group">
			<p><a class="button button--primary" href="/admin/users/create">Create a new user</a></p>
		</div>
	</header>

	<main>
		<ul class="listing">
			<?php foreach($users as $user): ?>
			<li>
				<h3><a href="<?php echo url('/admin/users/'.$user->id.'/edit'); ?>"><?php echo $user->name; ?></a></h3>
				<span class="badge--pinned">
					<span class="badge">
						<?php echo $user->role; ?>
					</span>
					<?php if( ! $user->isActive()): ?>
					<span class="badge">
						<?php echo $user->status; ?>
					</span>
					<?php endif; ?>
				</span>
				<p class="text--quiet"><?php echo $user->username; ?></p>
			</li>
			<?php endforeach; ?>
		</ul>

		<?php echo $paging->links(); ?>
	</main>
</div>
