<?php echo $form->open(); ?>

	<?php echo $messages; ?>

	<i class="anchor-logo">Anchor CMS</i>

	<?php foreach($form->getElementsExcluding(['submit']) as $element): ?>
	<?php if($element->hasLabel()): ?>
	<label for="<?php echo $element->getName(); ?>"><?php echo $element->getLabel(); ?></label>
	<?php endif; ?>

	<?php echo $element->getHtml(); ?>

	<?php endforeach; ?>

	<p><?php echo $form->getElement('submit')->getHtml(); ?></p>

<?php echo $form->close(); ?>
