<?php echo $form->open(); ?>

	<?php echo $form->getElement('token')->getHtml(); ?>

	<?php if(count($messages)): ?>
	<div class="messages">
		<?php foreach($messages as $type => $group): ?>
		<ul class="<?php echo $type; ?>">
			<?php foreach($group as $message): ?>
			<li><?php echo $message; ?></li>
			<?php endforeach; ?>
		</ul>
		<?php endforeach; ?>
	</div>
	<?php endif; ?>
    		
	<i class="anchor-logo">Anchor CMS</i>

	<?php foreach($form->getElementsExcluding(['submit']) as $element): ?>
	<?php if($element->hasLabel()): ?>
	<label for="<?php echo $element->getName(); ?>"><?php echo $element->getLabel(); ?></label>
	<?php endif; ?>

	<?php echo $element->getHtml(); ?>

	<?php endforeach; ?>

	<p><?php echo $form->getElement('submit')->getHtml(); ?></p>

<?php echo $form->close(); ?>