<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="robots" content="noindex,nofollow">
		<title><?php echo $title; ?></title>
		<link rel="stylesheet" href="/assets/css/main.css">
	</head>
	<body>
		<nav>
			<a href="/admin">Anchor CMS</a>
			<ul>
				<li><a href="/admin/posts">Posts</a></li>
				<li><a href="/admin/pages">Pages</a></li>
				<li><a href="/admin/categories">Categories</a></li>
				<li><a href="/admin/users">Users</a></li>
				<li><a href="/admin/fields">Custom Fields</a></li>
				<li><a href="/admin/vars">Global Variables</a></li>
				<li><a href="/admin/meta">Settings</a></li>
				<li><a href="/admin/themes">Themes</a></li>
				<li><a href="/admin/plugins">Plugins</a></li>
			</ul>
		</nav>
		<?php echo $body; ?>
	</body>
</html>
