
<h2>How are you going to log in?</h2>

<?php echo $messages; ?>

<?php echo $form->open(); ?>

<?php foreach($form->getElementsExcluding(['submit']) as $element): ?>
<p>
	<?php if($element->hasLabel()): ?>
	<label for="<?php echo $element->getName(); ?>"><?php echo $element->getLabel(); ?></label>
	<?php endif; ?>
	<?php echo $element->getHtml(); ?>
</p>
<?php endforeach; ?>

<p><a href="/metadata" class="button">Back</a>
	<?php echo $form->getElement('submit')->withAttribute('class', 'button button--primary float--right')->getHtml(); ?></p>

<?php echo $form->close(); ?>
