
<h2>How are you going to log in?</h2>

<?php echo $messages; ?>

<?php echo $form->open(); ?>

<?php foreach($form->getElementsExcluding(['submit']) as $element): ?>
<p>
	<?php if($element->hasLabel()): ?>
	<label for="<?php echo $element->getName(); ?>"><?php echo $element->getLabel(); ?></label>
	<?php endif; ?>
	<?php echo $element->getHtml(); ?>

    <?php if ($element->getName() == 'account_password'): ?>
        <progress value="0" max="4"></progress>
    <?php endif; ?>
</p>
<?php endforeach; ?>

<p><a href="/metadata" class="button">Back</a>
	<?php echo $form->getElement('submit')->withAttribute('disabled', '')->withAttribute('class', 'button button--primary float--right')->getHtml(); ?></p>

<?php echo $form->close(); ?>


<script>

    (function() {

        var timer;
        var password = document.querySelector('[name="account_password"]');
        var progress = document.querySelector('progress');
        var submit = document.querySelector('[type="submit"]');

        password.addEventListener('keyup', function(event) {
            clearTimeout(timer);
            timer = setTimeout(function() {
                var result = zxcvbn(password.value);
                progress.value = result.score;
                submit.disabled = progress.value < 1;
            }, 500);
        });

    })();

</script>