
<h2>What&apos;s your database details?</h2>

<?php echo $form->open(); ?>

<?php echo $messages; ?>

<?php foreach($form->getElements(['driver']) as $element): ?>
<p><label for="<?php echo $element->getName(); ?>"><?php echo $element->getLabel(); ?></label> <?php echo $element->getHtml(); ?></p>
<?php endforeach; ?>

<div class="mysql">
	<div class="multi">
	<?php foreach($form->getElements(['host', 'port']) as $element): ?>
		<p>
			<label for="<?php echo $element->getName(); ?>"><?php echo $element->getLabel(); ?></label>
			<?php echo $element->getHtml(); ?>
		</p>
	<?php endforeach; ?>
	</div>

	<div class="multi half">
	<?php foreach($form->getElements(['user', 'pass']) as $element): ?>
		<p>
			<label for="<?php echo $element->getName(); ?>"><?php echo $element->getLabel(); ?></label>
			<?php echo $element->getHtml(); ?>
		</p>
	<?php endforeach; ?>
	</div>
</div>

<?php foreach($form->getElementsExcluding(['driver', 'host', 'port', 'user', 'pass', 'submit']) as $element): ?>
<p><label for="<?php echo $element->getName(); ?>"><?php echo $element->getLabel(); ?></label> <?php echo $element->getHtml(); ?></p>
<?php endforeach; ?>

<p><a class="button" href="<?php echo $backUrl; ?>">Back</a>
	<?php echo $form->getElement('submit')->withAttributes(['class' => 'button button--primary float--right'])->getHtml(); ?></p>

<?php echo $form->close(); ?>

<script>
	(function(doc) {
		var select = doc.querySelector('select');

		var toggle = function() {
			doc.querySelector('.mysql').style.display = (select.options[select.selectedIndex].value == 'mysql') ? 'block' : 'none';
		};

		select.addEventListener('change', toggle, false);
		select.dispatchEvent(new Event('change'));
	})(document);
</script>
