<nav>
	<a class="anchor-logo">Anchor CMS</a>

	<ul>
		<li>Language and timezone</li>
		<li>Database setup</li>
		<li>Site metadata</li>
		<li>Your account</li>
		<li class="elapsed">All done!</li>
	</ul>
</nav>

<div class="content">
	<h1>Install complete!</h1>

	<p><a href="/admin" class="btn">Visit your admin panel</a>
		<a href="/" class="btn subdued">Visit your new site</a></p>
</div>

<small>
	You’re installing Anchor version 1.0.
	<a href="//twitter.com/anchorcms" target="_blank">Need help?</a>
</small>
