
<h2>Where in the world are you?</h2>

<?php echo $form->open(); ?>

<?php echo $messages; ?>

<?php foreach($form->getElementsExcluding(['submit']) as $element): ?>
<p><label for="<?php echo $element->getName(); ?>"><?php echo $element->getLabel(); ?></label> <?php echo $element->getHtml(); ?></p>
<?php endforeach; ?>

<p><?php echo $form->getElement('submit')->withAttributes(['class' => 'button button--primary'])->getHtml(); ?></p>

<?php echo $form->close(); ?>
