<h2>Tell us a little bit about your blog.</h2>

<?php echo $form->open(); ?>

<?php echo $messages; ?>

<?php foreach($form->getElementsExcluding(['submit']) as $element): ?>
<p><label for="<?php echo $element->getName(); ?>"><?php echo $element->getLabel(); ?></label> <?php echo $element->getHtml(); ?></p>
<?php endforeach; ?>

<p><a class="button" href="<?php echo $backUrl; ?>">Back</a>
	<?php echo $form->getElement('submit')->withAttributes(['class' => 'button button--primary float--right'])->getHtml(); ?></p>

<?php echo $form->close(); ?>
