
<?php echo $form->open(); ?>

	<?php echo $form->getElement('_token')->getHtml(); ?>

	<?php echo $this->render('partials/content', ['form' => $form]); ?>

	<div class="wrap">
		<p><?php echo $form->getElement('submit')->withAttributes(['class' => 'button button--primary'])->getHtml(); ?></p>
	</div>

<?php echo $form->close(); ?>

<?php echo $this->render('partials/messages-float', ['messages' => $messages]); ?>
