
<?php echo $form->open(); ?>

	<?php echo $form->getElement('_token')->getHtml(); ?>

	<?php echo $this->render('partials/content', ['form' => $form]); ?>

	<div class="wrap">
		<p><?php echo $form->getElement('submit')->withAttributes(['class' => 'button button--primary'])->getHtml(); ?>
			<a class="button button--danger" data-confirm="Are you sure?" href="/admin/pages/<?php echo $page->id; ?>/delete">Permanatly Delete</a></p>
	</div>

<?php echo $form->close(); ?>

<?php echo $this->render('partials/messages-float', ['messages' => $messages]); ?>
