<section class="content wrap narrow">
	<header class="filter">
		<a class="btn" href="/admin/pages/create">Create a new page</a>

		<div class="align-right">
			<form class="search" method="get" action="/admin/pages">
				<p><input placeholder="Search pages&hellip;" name="search"> <button type="submit">Search</button></p>
			</form>

			<ul class="split-options">
				<li <?php if(null === $filters['status']) echo 'class="active"'; ?>>
					<a href="/admin/pages">All</a>
				</li>

				<?php foreach($statuses as $status => $title): ?>
				<li <?php if($status == $filters['status']) echo 'class="active"'; ?>>
					<a href="/admin/pages?status=<?php echo $status; ?>"><?php echo $title; ?></a></li>
				<?php endforeach; ?>
			</ul>
		</div>
	</header>

	<main>
		<ul class="post-list">
			<?php foreach($pages as $page): ?>
			<li>
				<span class="badge <?php echo $page->status; ?>"><?php echo ucwords($page->status); ?></span>
				<a href="/admin/pages/<?php echo $page->id; ?>/edit">
					<h1 class="title"><?php echo $page->title; ?></h1>
					<p class="desc"><?php echo $page->content; ?></p>
				</a>

				<dl>
					<dt>Posted by</dt>
					<dd><a href="/admin/users/<?php echo $page->author; ?>">admin</a></dd>

					<?php if($page->parent): ?>
					<dt>Child of</dt>
					<dd><a href="/admin/pages/1">Parent page</a></dd>
					<?php endif; ?>

					<dt>Last edited</dt>
					<dd><?php echo $page->modified ? date('dS M y G:H', strtotime($page->modified)) : 'Never'; ?></dd>
				</dl>
			</li>
			<?php endforeach; ?>
		</ul>

		<?php echo $paging->links(); ?>
	</main>
</section>
