
<h2>Pages</h2>

<a href="/admin/pages/create">Create a new page</a>

<form method="get" action="/admin/pages">
	<p><input name="search" value=""> <button type="submit">Search</button></p>
</form>

<ul>
	<?php foreach($statuses as $status => $title): ?>
	<li><a href="/admin/pages?status=<?php echo $status; ?>"><?php echo $title; ?></a></li>
	<?php endforeach; ?>
</ul>

<ul>
	<?php foreach($pages as $page): ?>
	<li><a href="/admin/pages/<?php echo $page->id; ?>/edit"><?php echo $page->title; ?></a></li>
	<?php endforeach; ?>
</ul>

<?php echo $paging->links(); ?>
