
<div class="wrap">
	<header class="heading">
		<h2>Pages</h2>

		<div class="button-group">
			<form class="inline" method="get" action="/admin/pages">
				<p><input placeholder="Search pages&hellip;" name="search">
					<button class="btn" type="submit">Search</button>
					<a class="btn primary" href="/admin/pages/create">Create a new page</a></p>
			</form>
		</div>
	</header>

	<main class="grid">
		<div class="grid-col grid-1-4">
			<p>Filter by status</p>
			<ul>
				<li><a href="<?php echo url('/admin/pages'); ?>">All</a></li>
				<?php foreach($statuses as $status => $title): ?>
				<li><a href="/admin/pages?status=<?php echo $status; ?>"><?php echo $title; ?></a></li>
				<?php endforeach; ?>
			</ul>
		</div>

		<div class="grid-col grid-3-4">
			<ul class="listing">
				<?php foreach($pages as $page): ?>
				<li>
					<h3><a href="<?php echo url('/admin/pages/'.$page->id.'/edit'); ?>"><?php echo $page->title; ?></a></h3>
					<span class="badge <?php echo $page->status; ?>"><?php echo $page->status; ?></span>
				</li>
				<?php endforeach; ?>
			</ul>

			<?php echo $paging->links(); ?>
		</div>
	</main>
</div>
