<?php echo $form->open(); ?>

<?php echo $messages; ?>

<?php echo $form->getElement('token')->getHtml(); ?>

<div class="wrap split">
	<?php foreach($form->getElementsExcluding(['token']) as $element): ?>
	<p>
		<?php if($element->hasLabel()): ?>
		<label><?php echo $element->getLabel(); ?></label>
		<?php endif; ?>
		<?php echo $element->getHtml(); ?>
	</p>
	<?php endforeach; ?>
</div>

<?php echo $form->close(); ?>
