<?php echo $form->open(); ?>

<?php echo $messages; ?>

<?php echo $form->getElement('token')->getHtml(); ?>

<div class="title">
	<div class="wrap">
		<?php echo $form->getElement('title')->getHtml(); ?>

		<nav class="pull-right">
			<?php echo $form->withAttribute('class', 'button primary')->getElement('submit')->getHtml(); ?>
		</nav>
	</div>
</div>

<div class="wrap">
	<?php echo $form->getElement('content')->getHtml(); ?>
</div>

<div style="background: #ccd2d9">
	<div class="wrap split">
		<?php foreach($form->getElementsExcluding(['token', 'title', 'content', 'submit']) as $element): ?>
		<p>
			<label><?php echo $element->getLabel(); ?></label>
			<?php echo $element->getHtml(); ?>
		</p>
		<?php endforeach; ?>
	</div>
</div>

<?php echo $form->close(); ?>
