<?php echo $form->open(); ?>

<div class="title">
	<div class="wrap">
		<?php echo $form->getElement('title')->getHtml(); ?>

		<nav class="pull-right">
			<a class="button" href="#" target="preview">Preview</a>
			<?php echo $form->getElement('submit')->getHtml(); ?>
		</nav>
	</div>
</div>

<div class="media">
	<div class="wrap">
		<p>Uploads</p>

		<div class="collection">
			<?php foreach($this->media->get() as $file): ?>
			<?php var_dump($file); ?>
			<?php endforeach; ?>
		</div>
	</div>
</div>

<div class="wrap">
	<?php echo $form->getElement('html')->getHtml(); ?>
</div>

<script src="/app/views/assets/js/upload.js"></script>
<script>
	window.onerror = function() {
		return true;
	};

	$(function() {
		var el = $('textarea'), height = el.outerHeight(), scroll = el[0].scrollHeight;
		el.css('height', scroll + height);

		el.on('keyup', function() {
			var offset = $(window).scrollTop();

			scroll = el[0].scrollHeight;
			el.css('height', scroll);

			$(window).scrollTop(offset);
		});


		Upload.setup({
			bind: document.querySelector('.media .collection'),
			endpoint: '/admin/upload',
			start: function(file) {
				console.log('start', file);
			},
			progress: function(file, percent) {
				console.log('progress', file, percent);
			},
			complete: function(file, response) {
				console.log('complete', file);

				var html = '<figure><img src="/content/'+file.name+'"></figure>';

			}
		});

	});
</script>

<?php echo $form->close(); ?>
