<section class="content wrap narrow">
	<header class="filter">
		<a class="btn" href="/admin/posts/create">Create a new post</a>

		<div class="align-right">
			<form class="search" method="get" action="/admin/posts">
				<p><input placeholder="Search posts&hellip;" name="search"> <button type="submit">Search</button></p>
			</form>

			<ul class="split-options">
				<li <?php if(null === $filters['status']) echo 'class="active"'; ?>>
					<a href="/admin/posts">All</a>
				</li>

				<?php foreach($statuses as $status => $title): ?>
				<li <?php if($status == $filters['status']) echo 'class="active"'; ?>>
					<a href="/admin/posts?status=<?php echo $status; ?>"><?php echo $title; ?></a></li>
				<?php endforeach; ?>
			</ul>
		</div>
	</header>

	<main><!--
		<ul>
			<?php foreach($categories as $category): ?>
			<li><a href="/admin/posts?category=<?php echo $category->id; ?>"><?php echo $category->title; ?></a></li>
			<?php endforeach; ?>
		</ul> -->

		<ul class="post-list">
			<?php foreach($posts as $post): ?>
			<li>
				<span class="badge <?php echo $post->status; ?>"><?php echo ucwords($post->status); ?></span>
				<a href="/admin/posts/<?php echo $post->id; ?>/edit">
					<h1 class="title"><?php echo $post->title; ?></h1>
					<p class="desc"><?php echo $post->content; ?></p>
				</a>

				<dl>
					<dt>Posted by</dt>
					<dd><a href="/admin/users/<?php echo $post->author; ?>">admin</a></dd>

					<dt>Filed under</dt>
					<dd><a href="/admin/posts?category=<?php echo $post->category; ?>">Uncategorised</a></dd>

					<dt>Last edited</dt>
					<dd><?php echo date('dS M y G:H', strtotime($post->modified)); ?></dd>
				</dl>
			</li>
			<?php endforeach; ?>
		</ul>

		<?php echo $paging->links(); ?>
	</main>
</section>
