
<h2>Posts</h2>

<a href="/admin/posts/create">Create a new post</a>

<form method="get" action="/admin/posts">
	<p><input name="search" value=""> <button type="submit">Search</button></p>
</form>

<ul>
	<?php foreach($statuses as $status => $title): ?>
	<li><a href="/admin/posts?status=<?php echo $status; ?>"><?php echo $title; ?></a></li>
	<?php endforeach; ?>
</ul>

<ul>
	<?php foreach($categories as $category): ?>
	<li><a href="/admin/posts?category=<?php echo $category->id; ?>"><?php echo $category->title; ?></a></li>
	<?php endforeach; ?>
</ul>

<ul>
	<?php foreach($posts as $post): ?>
	<li><a href="/admin/posts/<?php echo $post->id; ?>/edit"><?php echo $post->title; ?></a></li>
	<?php endforeach; ?>
</ul>

<?php echo $paging->links(); ?>
