<div class="wrap">

	<div class="clearfix">
		<h1 class="pull-left">Categories</h1>

		<nav class="pull-right">
			<p><a class="button" href="/admin/categories/create">Create</a></p>
		</nav>
	</div>

	<div class="column full first last">
		<?php foreach($categories as $category): ?>
		<a class="item" href="/admin/categories/<?php echo $category->id; ?>/edit">
			<strong><?php echo $category->title; ?></strong>
			<span><?php echo $category->slug; ?></span>
		</a>
		<?php endforeach; ?>

		<nav class="paging"><?php echo $paging->links(); ?></nav>
	</div>

</div>
