
<div class="wrap">
	<header class="heading">
		<h2>Custom Fields</h2>

		<div class="button-group">
			<p><a class="button button--primary" href="/admin/fields/create">Create a new custom field</a></p>
		</div>
	</header>

	<main>
		<ul class="listing">
			<?php foreach($fields as $field): ?>
			<li>
				<h3><a href="/admin/fields/<?php echo $field->id; ?>/edit"><?php echo $field->label; ?></a></h3>
				<span class="badge badge--pinned"><?php echo $field->content_type; ?> <?php echo $field->input_type; ?></span>
			</li>
			<?php endforeach; ?>
		</ul>
	</main>
</div>
