<section class="content wrap narrow">
	<main>
		<?php if(empty($fields)): ?>
			<span class="empty-state">No custom fields added yet!<br>You can create one below.</span>
		<?php else: ?>
		<ul>
			<?php foreach($fields as $field): ?>
			<li>
				<a href="/admin/fields/<?php echo $field->id; ?>/edit"><?php echo $field->label; ?> <?php echo $field->field; ?></a>
			</li>
			<?php endforeach; ?>
		</ul>
		<?php endif; ?>

		<?php echo $paging->links(); ?>
	</main>

	<footer class="new">
		<?php echo $this->render('partials/form', ['form' => $form]); ?>
	</footer>
</section>