<!doctype html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta name="robots" content="noindex,nofollow">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=1400, initial-scale=1">

        <title><?php echo $title; ?></title>

		<!-- Compiles from LESS -->
        <link rel="stylesheet" href="<?php echo asset('assets/css/admin.css'); ?>">
    </head>
	<body class="auth">
		<?php echo $body; ?>
	</body>
</html>
