<?php

$menu = [
	'/admin/posts' => 'Posts',
	'/admin/pages' => 'Pages',
	'/admin/categories' => 'Categories',
	'/admin/users' => 'Users',
	'/admin/extend' => 'Extend',
];

$active = '';

define('USE_MINIFIED', true);

function path($to = '', $min = false) {
    if($min !== false and USE_MINIFIED === true) {
        echo '/app/views/assets/' . $min;
        return;
    }

	echo '/app/views/assets/' . $to;
}

?><!doctype html><html class="no-js" lang="en-gb">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title><?php echo $title; ?> — Anchor CMS</title>

        <meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- Compiles from LESS -->
        <link rel="stylesheet" href="<?php path('anchor.css'); ?>">
        <link rel="stylesheet" href="<?php path('js/pen/pen.css'); ?>">

        <!-- Compiles from current theme, if it exists -->
        <link rel="stylesheet" href="/themes/current/admin-custom.css">
    </head>
    <body class="<?php if(isset($class)) echo $class; ?>">

        <nav class="main-nav">
            <ul class="actions">
                <?php foreach(['posts', 'comments', 'pages', 'menu', 'categories'] as $link): ?>
                <?php $title = ucwords($link); ?>
                <li class="<?php if(strpos($active, '/admin/' . $link) !== false) echo 'active'; ?>">
                    <a href="/admin/<?php echo $link; ?>"><?php echo $title; ?></a>
                </li>
                <?php endforeach; ?>
            </ul>

            <a class="anchor-logo">Anchor CMS</a>

            <ul class="results">
                <li>
                    <a href="../admin"><?php echo _('View site'); ?></a>
                </li>

                <?php foreach(['users' => 'Users', 'extend' => 'Settings', 'logout' => 'Log out'] as $link => $title): ?>
                <li class="<?php if(strpos($active, '/admin/' . $link) !== false) echo 'active'; ?>">
                    <a href="/admin/<?php echo $link; ?>"><?php echo $title; ?></a>
                </li>
                <?php endforeach; ?>
            </ul>
        </nav>

    	<?php echo $body; ?>

		<!-- JS wankery -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="<?php path('js/vendor/jquery-1.11.1.min.js'); ?>"><\/script>')</script>

        <!-- Editor JS -->
        <script src="<?php path('js/pen/pen.js'); ?>"></script>
        <script src="<?php path('js/pen/markdown.js'); ?>"></script>

        <script src="<?php path('js/vendor/jquery-hotkeys.min.js'); ?>"></script>
        <script src="<?php path('js/admin.js', 'js/min/admin-min.js'); ?>"></script>
        <script src="<?php path('js/editor.js', 'js/min/editor-min.js'); ?>"></script>

        <script>
        	// Confirm any deletions
        	$('.delete').click(function() {return confirm('Are you sure?')});
        </script>
    </body>
</html>
