<?php
	$age = nth($content);
	$ordinal = ordinal($age);
?>
<article class="wrap">
	<hgroup>
		<h1><?php echo article_title(); ?></h1>
		<p>Posted by <?php echo article_author(); ?> <em>on the <?php echo article_date(); ?></em></p>
	</hgroup>

	<div class="article-content">
		<?php echo article_content(); ?>
	</div>

	<small>
		<p>This article is my <?php echo $age > 1 ? $ordinal . ' oldest' : $ordinal; ?>. It is <?php echo words($content); ?> words long.</p>
	</small>
</article>

<section class="related-content">

</section>
