<?php
	$age = nth($content);
	$ordinal = ordinal($age);
?>
<article class="wrap">
	<hgroup>
		<h1><?php echo $content->title; ?></h1>
		<p>Posted by <?php echo $content->getAuthor()->getName(); ?> <em>on the <?php echo $content->getDate('dS M Y'); ?></em></p>
	</hgroup>

	<div class="article-content">
		<?php echo $content->html; ?>
	</div>

	<small>
		<p>This article is my <?php echo $age > 1 ? $ordinal . ' oldest' : $ordinal; ?>. It is <?php echo words($content); ?> words long.</p>
	</small>
</article>

<section class="related-content">

</section>
