<aside class="site-description wrap">
	<h1>
		<?php echo $meta->description; ?>
	</h1>
</aside>

<ul class="stories wrap">
	<?php while($content->loop()): ?>
	<li>
		<hgroup>
			<h1>
				<a href="/<?php echo $page->slug; ?>/<?php echo $content->slug; ?>">
					<?php echo $content->title; ?>
				</a>
			</h1>

			<small>Posted by <?php echo fallback(!$content->author, 'Administrator'); ?> <em>on the <?php echo date('dS M Y'); ?></em></small>
		</hgroup>

		<div class="article-excerpt">
			<?php echo $content->body(); ?>
		</div>
	</li>
	<?php endwhile; ?>
</ul>

<section class="related-content">
	<div class="wrap">
		<div class="half-width">
			<h2>Categories</h2>

			<ul>
				<?php while($categories->loop()): ?>
				<li>
					<a href="/category/<?php echo $categories->slug; ?>" title="<?php echo $categories->description; ?>">
						<?php echo $categories->title; ?>

						<small><?php echo $categories->postCount(); ?></small>
					</a>
				</li>
				<?php endwhile; ?>
			</ul>
		</div>

		<div class="half-width">
			<h2>Search my blog</h2>

			<form>
				<input type="search" placeholder="Search anything here.">
				<button type="submit">Search</button>
			</form>
		</div>
	</div>
</section>
