<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title><?php echo page_title(); ?> &mdash; <?php echo site_name(); ?></title>
		<meta name="description" content="<?php echo $meta->description; ?>">

		<link rel="stylesheet" href="<?php echo asset_url('assets/css/styles.css'); ?>">
	</head>
	<body class="<?php echo $page->slug; ?>">
		<header>
			<a href="<?php echo base_url('/'); ?>" class="logo"><?php echo $meta->sitename; ?></a>

			<nav>
				<ul>
					<?php while($menu->loop()): ?>
					<li <?php if($menu->slug == $page->slug) echo 'class="active"'; ?>>
						<a href="<?php echo base_url($menu->slug); ?>"><?php echo $menu->title; ?></a>
					</li>
					<?php endwhile; ?>
				</ul>
			</nav>
		</header>

		<section class="content">
			<?php echo $body; ?>
		</section>

		<footer>
			<div class="wrap">
				<ul>
					<li><a href="<?php echo base_url('/feeds/rss'); ?>">RSS</a></li>
					<li><a href="https://twitter.com/anchorcms">@anchorcms</a></li>
					<li><a href="<?php echo base_url('/admin'); ?>" title="Administer your site!">Admin area</a></li>
					<li><a href="<?php echo base_url('/'); ?>'" title="Return to my website.">Home</a></li>
				</ul>

				<p>&copy; <?php echo date('Y'); ?> <?php echo $meta->sitename; ?>. All rights reserved.</p>
			</div>
		</footer>
	</body>
</html>
