<?php

$age = nth($content);
$ordinal = ordinal($age);
$words = words($content);


?><div class="items">
	<div class="item">
		<div class="wrap">
			<h1><?php echo $content->title; ?></h1>

			<div class="content"><?php echo $content->body(); ?></div>

			<p>This article is my <?php echo ($age > 1 ? $ordinal . ' oldest' : $ordinal); ?>. It is <?php echo $words; ?> words long.</p>
		</div>
	</div>
</div>
