<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title><?php echo $page->title; ?> &mdash; <?php echo $meta->sitename; ?></title>
		<meta name="description" content="<?php echo $meta->description; ?>">
	</head>
	<body>
		<header>
			<a href="/" class="logo"><?php echo $meta->sitename; ?></a>
		</header>

		<nav>
			<ul>
				<?php while($categories->loop()): ?>
				<li>
					<a href="/category/<?php echo $categories->slug; ?>" title="<?php echo $categories->description; ?>">
						<?php echo $categories->title; ?>
					</a>
				</li>
				<?php endwhile; ?>
			</ul>

			<ul>
				<?php while($menu->loop()): ?>
				<li><a href="/<?php echo $menu->slug; ?>"><?php echo $menu->title; ?></a></li>
				<?php endwhile; ?>
			</ul>
		</nav>

		<?php echo $body; ?>

		<footer>
			<nav>
				<ul>
					<li><a href="/feeds/rss">RSS</a></li>
					<li><a href="https://twitter.com/anchorcms">@anchorcms</a></li>
					<li><a href="/admin" title="Administer your site!">Admin area</a></li>
					<li><a href="/" title="Return to my website.">Home</a></li>
				</ul>
			</nav>
			<p>&copy; <?php echo date('Y'); ?> My First Anchor Blog. All rights reserved.</p>
		</footer>
	</body>
</html>
