<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="robots" content="noindex,nofollow">
		<title><?php echo $title; ?></title>
		<link rel="icon" type="image/svg+xml" href="/assets/img/logo.svg">
		<link rel="stylesheet" href="/assets/css/main.css">
	</head>
	<body class="body--dark body--margin">
		<?php echo $body; ?>
	</body>
</html>
