<?php echo $form->open(); ?>

	<?php echo $form->getElement('token')->getHtml(); ?>

	<?php foreach($form->getElementsExcluding(['submit', 'token']) as $element): ?>

	<p>
		<?php if($element->hasLabel()): ?>
		<label for="<?php echo $element->getAttribute('name'); ?>"><?php echo $element->getLabel(); ?></label>
		<?php endif; ?>

		<?php echo $element->getHtml(); ?>
	</p>

	<?php endforeach; ?>

	<p>
		<?php echo $form->getElement('submit')->withAttributes(['class' => 'btn'])->getHtml(); ?>
	</p>

<?php echo $form->close(); ?>
